### ISSUE TITLE
CRD v2 - Support dynamically creating and managing pools

### ISSUE THREAD

**Issue by coryodaniel** [coryodaniel/ballast#17]
Implement as a new `kind` to continue to support users that want to define their own pools.

```yaml
kind: PoolGroupPolicy
metadata:
  name: k8s-pool-name
spec:
  cluster: demo
  minimumInstances: 10
  maximumInstance: 100
  percentPreemptible: 50
  # 50% of what? cpu or pod count or memory or mix???
  percentMetric: cpu 
  # preemptibleTypes, onDemandTypes ~optional
  preemptibleTypes: # preemptible can use these types
  - n1-standard-1
  - n1-standard-2
  onDemandTypes: # ondemand can use these types
  - n1-standard-1
  - n1-standard-2  
  locations: # specify the regions/zones to use
  - us-central-1a
  - us-central-1
```

Need support other fields for taints, labels, etc.
